### ISSUE TITLE
updating to latest but need advice...

### ISSUE THREAD

**Issue by ironsheep** [custom-cards/custom-card-helpers#34]
My use of 

```
relativeTime(new Date(stateStrInterp), this.hass?.localize);
```

has been returning an empty string for a while now.  Your latest updates show the parameters have changed for both computeStateDisplay() and relativeTime(). which I use. 

I've not been able to find any examples for how to get/specify the FrontEndTranslationData which is now needed.  Do you have any advice? Examples?   (I wish the doc also contained example invocations for these methods.  I'm fairly new at this but have a couple of published cards already ;-)

**Comment by iantrich** [comment]
CC @JonahKr

**Comment by vinteo** [comment]
Hi, I believe this https://github.com/custom-cards/custom-card-helpers/pull/36 fixes it

**Comment by ironsheep** [comment]
Hi, I'm back and still just as unsuccessful.

The issue is that I've spent hours twice now trying to figure out how to call these methods.

The 2nd time the parameters have changed yet again.  Can someone please provide examples for how to call these methods in the latest version of these helpers... ??  

I even found https://custom-cards.github.io/custom-card-helpers/ which is pretty but does not show any example invocations of any of the methods. 

I'm attempting to use **computeStateDisplay()** and **relativeTime()**

I apologize if I'm new enough that you deem that this was obvious.  Please feel free to send me to examples to study.

Here's what I think I should be doing but it doesn't compile due to the new third parameter data type changing. I'm trying to make the change but am unsuccessful.

```
private _getRelativeTimeSinceUpdate(): string {
    const stateObj = this._config.entity ? this.hass.states[this._config.entity] : undefined;
    // xxxeslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const stateStrInterp = computeStateDisplay(this.hass?.localize, stateObj!, this.hass?.locale);
    const relativeInterp =
      stateStrInterp === undefined ? '{unknown}' : relativeTime(new Date(stateStrInterp), this.hass?.localize);
    const desiredValue = this._sensorAvailable ? relativeInterp : '{unknown}';
    return desiredValue;
  }

  private _getMinutesSinceUpdate(): number {
    const stateObj = this._config.entity ? this.hass.states[this._config.entity] : undefined;
    // xxxeslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const stateStrInterp = computeStateDisplay(this.hass?.localize, stateObj!, this.hass?.locale);
    const then = new Date(stateStrInterp);
    const now = new Date();
    let diff = (now.getTime() - then.getTime()) / 1000;
    diff /= 60;
    return Math.abs(Math.round(diff));
  }
```
